\documentclass{article}
\usepackage{Sweave}
\usepackage{float}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage[svgnames]{xcolor}
\usepackage[T1]{fontenc}
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,      
    urlcolor=cyan,
}

\urlstyle{same}
\usepackage{tabularx}
\usepackage{siunitx}
\usepackage{amssymb} % for math symbols
\usepackage{amsmath} % for aligning equations
\usepackage{textcomp}
\usepackage{mdframed}
\usepackage{natbib}
%\bibliographystyle{..//references/styles/besjournals.bst}
\usepackage[small]{caption}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%\pagestyle{empty} %comment if want page numbers
\parskip 7.2pt
\renewcommand{\baselinestretch}{1.5}
\renewcommand{\rmdefault}{qag} % Arial
\renewcommand{\sfdefault}{qag} % Arial
\parindent 0pt
%\usepackage{lineno}
%\linenumbers

\newmdenv[
  topline=true,
  bottomline=true,
  skipabove=\topsep,
  skipbelow=\topsep
]{siderules}

\begin{document}

\noindent {\LARGE{\textbf{Landowner Document: OUTLINE}}}
\vspace{3ex}\\
{\Large{\textbf{Family Forest Carbon Program}}}
  \begin{itemize}
  
  \item Your land not only impacts you and your community but also the plants and wildlife that call your land home. The decisions you make about your land can also greatly impact the climate. Forests are one of the few natural and essential tools we have to draw down carbon from the atmosphere and turn it into wood, roots and soil.
  \item  The most important thing you can do to help fight climate change is to ensure that your land remains a forest now and to decide what will happen to your forest in the future.
  \item That is why the decisions you make about managing your land can be a major positive influence on our environment and benefit forest income, wildlife, provide clean water, establish a resilient ecosystem and mitigate climate change. %%How you manage your land also plays a role.
    % TODD: I think #4 is a key piece. Many landowners will think “If forests are so important, why not just leave them be?” I see two ways of approaching this: for landowners already actively managing or thinking about it, they can see that thoughtful and intentional management doesn’t need to be at odds with climate mitigation. For those that aren’t thinking about active management, this program might be an entry point to thinking about how management can benefit other goals they have for their forest (income, wildlife, water, RESILIENCE) and may help to store addition carbon in the forest relative to what the average landowner might do.  
  \end{itemize}
 
\begin{centering}   
\fbox{ {\setlength{\fboxrule}{2pt}
\begin{minipage}{6.5 in}
{\large{\textbf{\textcolor{DarkGreen}{FOREST RESILIENCE:}}}}\\
  Our forests are vulnerable to land conversion, invasive plants, insects, and diseases, heavy deer and moose browsing and climate change. This is why the role of management is so crucial. Your forest provides clean water, wildlife habitats, recreational opportunities and forest products while also sequestering carbon from the atmostphere. By managing your forest and keeping your forest a forest, it will continue to be resilient and help reduce the risks of climate change. 
  \end{minipage}}}
\end{centering}

  \begin{itemize}
  \item Your forest may be small but landowners like you own XX\% of New England and New York forests. The small forest size has often made it challenging to access incentive programs that can help you to do carbon-beneficial forest management on your land.
  
  \item The Family Forest Carbon Program, which is a collaboration between the American Forest Foundation and the Nature Conservancy, works with you to mitigate climate change and maintain resilient forests. 

  {\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=16cm]{..//figures/TNC-forestC.pdf}\label{fig:carbon}
  -\end{center}
  -\end{figure}}

  %\item Across the United States, 38\% of forests are owned by families or individuals. The majority of forest landowners have 20 to 500 acres but these families are unable to contribute to carbon markets due to high costs and inaccessibility.  By implementing the Family Forest Carbon Program into New England, we can help resolve some of these complexities by increasing our carbon sequestration potential by opening XXX million acres of forestland. 
  
   
  \end{itemize}

{\Large{\textbf{Is the Family Forest Carbon Program a good fit for you?}}} \\
\vspace{2ex}\\
{\large{\textbf{Benefits include:}}}
  \begin{itemize}
  \item Payments to help cover the cost of managing your land: sources include public dollars to grow more carbon and improve other forest values, private foundations with an interest in forests, or carbon credits traded in carbon markets.
  \item Improved Land: foresters assigned to each parcel will help family forest owners protect their water resources, build more resilient forests and promote a better wildlife habitat for the future.
  \item Local Community Engagement: rural Americans will be supported and will benefit economically.
  \end{itemize}

{\Large{\textbf{The Family Forest Carbon Practices}}}
  \begin{itemize}
  \item This program began in response to the early- and mid-stage carbon markets, which were generally ineffective for family forest landowners in New England due to large parcel size requirements. The Family Forest Carbon Program helps family forest landowners design and implement a 20-year forest management plan that focuses on carbon sequestration---primarily on the carbon stored in trees, or the aboveground carbon stock. 
  \item Simultaneously, we aim to take a practice-based approach to best suit \textit{your} needs and to manage your forest the way you want it to be managed. It is crucial that you don't lose sight of the reasons you own and enjoy your woods: whether it is a place to enjoy nature, a home for wildlife, a family legacy you wish to protect, a financial investment, a source of heat or maple syrup or furniture or lumber from the wood you harvest. Your management decisions should reflect all of your values---managing simply for a short-term increase in carbon stock makes as little sense as managing just for a short-term economic gain.
  \item The Family Forest Carbon Program includes 10 possible practices, which are considered ``good for the climate'' and were first established in 2019 by a team from the Nature Conservancy, American Forest Foundation and the US Forest Service. With help from a group of 20 stakeholders---including County and Service foresters, private consulting foresters, loggers, forestry professors, land trusts, and others---we narrowed these existing resources down to the ten practices listed below. 
  \item These practices increase carbon stock and benefit the land on which they are applied within 20 years (the timeframe of the Family Forest Carbon Program contracts). Most of these practices show carbon benefits immediately. A few, such as reforestation, take several years to begin showing carbon benefits.
  \item All of the practices on this list are long-term commitments that positively affect the environment and enhance habitats for wildlife. We did not rank these practices and we have no intention to dictate which practice is the ``best'' option for you, and we certainly don't want to determine which is the ``best'' one for your neighbor! This a personal decision for you to make with your forester, thinking about all the values of your forest and what will leave you feeling good about and the impact you have made. In an ideal world, we'd like to see different landowners choose different practices but all practices are deemed essential and a crucial step towards positive change.
  \item All forests are different and the conditions of your forest will likely best match one or two of these practices. Your forester will help you make that determination. It's not entirely up to you what is best for your forest and the environment, but by openly and clearly communicating with your forester, you can chose the best practice to match your needs and values. 
  
  {\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=8cm]{..//figures/forestimage.png}\label{fig:forest}
  -\end{center}
  -\end{figure}}
  
  \item By joining the Family Forest Carbon Program, you will become part of a team which includes: 
    \begin{enumerate}
    \item A Forester: who can speak with you and visit your land to provide advice on management options and program opportunities. A forester can help you design a plan that fits your values and most makes sense for your landscape.
    \item A Logger/Harvester: who will mark trees and help carry out the management plan that best suits you and your forest's needs.
    \item And most importantly you! You must share what is most important to you with your forester so that the forester and harvester can help you maintain what you value about your forest. 
    \end{enumerate}

  \item You and your team will then develop a forest management plan that follows one of the 10 possible practices: (please note the first four practices are not eligible for FFCP payments)
  \item NOTE: we need a few sentence narrative descriptions of each individual practice (Cat has added some contet, Todd and Laura to help edit)

    \begin{enumerate}
    \item Avoid forest loss: Reduce or eliminate conversion of forest to non-forest use since forest lands contain more carbon than most other land uses.
    \item Avoiding pre-salvage logging: Leaving dead or dying trees and allowing natural mortality and decomposition from disturbances. For example, leaving hemlock or ash to add carbon to soil and downed wood carbon pools. Also, avoiding salvage logging following severe natural disturbances, (e.g. hurricanes, tornadoes, ice storms). 
    \item Extending cutting cycles: Expanding from one 10-year management plan to two consecutive plans to allow for 10 years of additional growth before harvest.
    \item Planting trees along streets and in yards: Tree planting in urban and residential areas to increase overall sequestration and storage from enhancing the tree canopy. 
    \item Reforestation: Through seeding, stocking or passive reforestation, create a forest with a diversity of trees that reduce the risk of climate change.
    \item Creating regeneration with complexity: When forests are undergoing harvests, retention of a minimum number of large-diameter live trees, snags (see NEFF's Exemplary Forestry standards), and live-but-dying trees (future snags), enhancement of coarse woody debris, and limiting gap creation to 15\% to no more than 20\% of the parcel.
    \item Retaining more carbon in thinnings: Increased retention of live trees and slash during thinning practices, resulting in greater post-harvest stocking. Retain trees of a diversity of species.
    \item Establishing reserves: No harvesting over a 20-year period with intent to continue beyond 20 years (with exceptions for invasive removals or novel outbreaks of forest pests and pathogens). Preference given to sites with high carbon density (may include: soil organic carbon threshold; old growth characteristics---such as all-aged conditions, abundant CWD, large diameter trees) and low vulnerability sites with high species diversity or species composition with high proportion of future-adapted species. Reserves can cover an entire parcel, or can occur on part of a parcel. 
    \item Protecting regeneration from deer and moose: Actions to reduce over-browsing and protect regeneration from animal damage. Practices may include use of tree shelters, exclusion fencing, bud capping, or repellent sprays to reduce herbivore damage to desirable regeneration or planted stock. 
    \item Removing competing vegetation: Removal of heavy infestations of invasives that compete with regeneration, either pre- or post-harvest, or both. May include treatments designed to prevent the establishment of invasives (e.g. herbiciding).
    \end{enumerate}

  \item NOTE HERE: CAT NEEDS HELP WITH THIS INFORMATION
  \begin{itemize}
    \item Most of these practices require a 20 year contract and some require more than one year of activity on the land. Discussion of time commitment required for the program (in most cases, 20 year contract; for some practices, it will require more than one year’s worth of activity on the land, for example invasive treatments almost always have to be repeated)
    \item By the time of any payments, landowners must have a forest management or forest stewardship plan (do not need one at program entry)
    \item In all practices, you must maintain healthy soils.
    \item Risk (payments aren't guaranteed especially for practices with performance standards)
  \end{itemize}
  \end{itemize}
  
{\Large{\textbf{Eligible families and individuals}}}\\
\begin{itemize}
\item Eligible landowners must meet the following criteria:
  \begin{enumerate}
  \item The property is within the eligible project areas (see maps below)
  \item The property is between 30 and 2,400 acres of non-industrial private forestland
  \item The property is not subject to any existing legal encumbrance (e.g. conservation easement or
state/local restrictions) that excludes timber harvest activity (e.g. riparian buffers, designated reserves or no harvest areas)
  \end{enumerate}
\end{itemize}

{\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=14cm]{..//figures/programmapDRAFT.png}\label{fig:map}
  -\end{center}
  -\end{figure}}


{\Large{\textbf{Why the Family Forest Carbon Program is so important now}}}

  \begin{itemize}
  \item Forests help fight the adverse effects of climate change by pulling carbon from the atmosphere and turning it into wood, roots and soil. The primary aim of the Family Forest Carbon Program will always be ``avoiding forest loss''. From a carbon standpoint, when a forest is converted to another land-use, a portion of the carbon stored in its trees is immediately lost as trees are cut, roots decay, and wood that isn't valuable enough to sell is often piled on site or used as mulch and other short-lived products. Every year after that, we lose carbon sequestration. Often called ``foregone sequestration'', this refers to the carbon that the forest used to pull from the atmosphere each year and turn into wood, roots, and soil.
  
  \item In New England, we lose 77 acres of forestland each day, which is over 28,000 acres in a year (Olofsson et al., 2016). The most important thing you can do as a family forest landowner is to keep your forest a forest so your trees can continue to sequester carbon and combat climate change.

  \item Though forestland is important to maintain, harvested wood is still important. Once dried, wood is about 50\% carbon. In Massachusetts, the oldest timber frame (? Check with Jessica's article?) in the US is still standing, holding significant amounts of carbon from trees harvested in the 1600s. As states and countries and the world think about forests and climate change, they are trying to make sure that the wood we use is sustainably harvested (which yours will be), and that we don't take actions in places that have climate change policies in place (like New England) that reduce wood production here to the point that people start using less sustainable products that take more carbon to produce and ship.

  \item So not only is it important to avoid forest loss but it is also important that you pay particular attention to what wood products you generate and how these products can be used to store carbon in the long-term. None of these practices allow poor land management (``take the best and leave the rest''), large-scale clearcutting, or short-term decisions that reduce the ability of the forest to provide wood or sequester carbon in the future. If you are choosing from our list of carbon-beneficial practices, the wood that comes out of those harvests is sustainable. Wood that is used to substitute for more carbon-intensive materials, like concrete, steel, heating oil, or irresponsibly harvested wood from tropical forests or from forests on the other side of the globe has a huge carbon benefit. In this program specifically, we are not paying landowners for that carbon value, but that does not mean that it should be ignored as you think about how to manage your land.

  \item The Family Forest Carbon Program model is based on the idea that many carbon-beneficial practices cost landowners money, at least in the near term. The FFCP is paying for a change in behavior from the ``common practice'' or ``business as usual'' harvest to one that might leave more standing dead trees on site, to harvest less intensively, pay to remove invasive plants or build fences to keep out deer. All of those things cost the landowner money. For many of you, part of the money from a harvest will come from the FFCP, and then additional income will come from selling wood. Since wood is a form of forest carbon that has a value in the marketplace already, we don't include payments for it in the Family Forest Carbon Program.

  \item Another financial benefit of the program is it allows landowners and foresters to track carbon stock changes more effectively and less expensively. In most traditional carbon markets, carbon is calculated by taking forest carbon inventories, which is costly. By joining the Family Forest Carbon Program, you will reduce your expenses by 75\% compared to if you used more traditional carbon markets. 

  \item All of these practices should continue to produce carbon benefits every year after the 20 year contract, barring things like insect outbreaks, natural disasters, or---most importantly---conversion of the land to development. As a landowner, you should feel good about any practice on this list (we certainly do!).

  \end{itemize}


\end{document}